# Generated by Django 3.2.5 on 2022-01-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
